name: My First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Simple Greeting!"
        run: echo "Hello World!!!!"
      - name: "Terminating"
        run: echo "Done!!!"
      
